version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=db/development.sqlite3
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
